### ISSUE TITLE
Run without Docker

### ISSUE THREAD

**Issue by adeelhussain** [Haufe-Lexware/wicked.portal-api#1]
Is there any documentation available for running this without docker?

**Comment by DonMartin76** [comment]
Hi there,

Yes, see here: https://github.com/Haufe-Lexware/wicked.haufe.io/blob/master/doc/development-environment.md

If you wait until 0.10.0 has been released (due tomorrow, if everything works out), it will work just as described in the above document. Before that, things are more tricky, so I recommend waiting until the merge has been done.

Best regards,
Martin

**Comment by adeelhussain** [comment]
Thanks for the response :) I will try and hope everything would work fine 😄
